id: product_ux_flow_copy_synthesizer_v1
name: Product-Ux-Flow-Copy-Synthesizer-V1
description: 'tools: ["Question", "Task", "Bash"]'
category: analysis
tags:
- product
- flow
- analysis
- copy
- synthesizer
default_complexity: simple
default_tools:
- FileReadTool
- CodeInterpreterTool
sample_prompts:
- Run this agent for specialized task execution.
suggested_config:
  llm_provider: openai
  model: gpt-4o
  include_memory: true
  max_agents: 1
agent_structure:
  agents:
  - name: primary_agent
    role: Product-Ux-Flow-Copy-Synthesizer-V1 specialist
    backstory: Expert product-ux-flow-copy-synthesizer-v1 with deep domain knowledge.
expected_outputs:
- Task completion report
- Analysis summary
- Recommendations
