/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/generate-agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate agent from description
         * @description Generate a complete CrewAI agent from a natural language description.
         *     Returns Python code following the Godzilla pattern, agent configuration,
         *     and estimated complexity.
         */
        post: operations["generateAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate agent with modifications
         * @description Regenerate an agent with specific modifications or different parameters
         */
        post: operations["regenerateAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate generated code
         * @description Validate Python code against the Godzilla pattern requirements.
         *     Checks syntax, structure, and best practices.
         */
        post: operations["validateCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get validation rules
         * @description Returns the list of validation rules used for code checking
         */
        get: operations["getValidationRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List saved agents
         * @description Retrieve a paginated list of all saved agents
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get agent details */
        get: operations["getAgent"];
        /** Update agent */
        put: operations["updateAgent"];
        post?: never;
        /** Delete agent */
        delete: operations["deleteAgent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the service and its dependencies
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Returns whether the service is ready to accept requests
         */
        get: operations["readinessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns whether the service is alive
         */
        get: operations["livenessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenerateAgentRequest: {
            /**
             * @description Natural language description of the agent
             * @example Create a web research agent that searches for information and summarizes findings
             */
            description: string;
            /**
             * @description Desired complexity level
             * @default moderate
             * @enum {string}
             */
            complexity: "simple" | "moderate" | "complex";
            /**
             * @description Type of task the agent will perform
             * @default general
             * @enum {string}
             */
            task_type: "research" | "development" | "automation" | "analysis" | "general";
            /**
             * @description Maximum number of agents to generate
             * @default 3
             */
            max_agents: number;
            /**
             * @description Specific tools to include
             * @example [
             *       "web_search",
             *       "file_read",
             *       "code_execution"
             *     ]
             */
            tools_requested?: string[];
            /**
             * @description LLM provider to use for generation
             * @default zai
             * @enum {string}
             */
            provider: "zai" | "openai" | "anthropic" | "openrouter";
            /**
             * @description Whether to save the generated agent
             * @default true
             */
            save_agent: boolean;
        };
        GenerateAgentResponse: {
            /**
             * Format: uuid
             * @description Unique identifier for the generated agent
             */
            agent_id?: string;
            /**
             * @description Generated Python code following Godzilla pattern
             * @example from crewai import Agent, Task, Crew, Process
             *     from crewai.flow.flow import Flow, listen, start
             *     ...
             */
            flow_code?: string;
            /** @description YAML configuration for agents */
            agents_config?: Record<string, never>;
            /** @description Original description */
            description?: string;
            /** @enum {string} */
            complexity?: "simple" | "moderate" | "complex";
            task_type?: string;
            /** @description Number of agents generated */
            agent_count?: number;
            tools_included?: string[];
            validation_passed?: boolean;
            warnings?: string[];
            /** Format: date-time */
            created_at?: string;
        };
        ValidateCodeRequest: {
            /** @description Python code to validate */
            code: string;
            /**
             * @description Enable strict validation
             * @default false
             */
            strict_mode: boolean;
        };
        ValidateCodeResponse: {
            is_valid?: boolean;
            errors?: {
                line?: number;
                column?: number;
                message?: string;
                /** @enum {string} */
                severity?: "error" | "warning" | "info";
            }[];
            warnings?: {
                line?: number;
                message?: string;
            }[];
            /**
             * Format: float
             * @description Quality score (0-100)
             */
            score?: number;
            suggestions?: string[];
        };
        AgentListResponse: {
            agents?: components["schemas"]["AgentSummary"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        AgentSummary: {
            /** Format: uuid */
            agent_id?: string;
            description?: string;
            complexity?: string;
            task_type?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AgentDetailResponse: {
            /** Format: uuid */
            agent_id?: string;
            description?: string;
            flow_code?: string;
            agents_config?: Record<string, never>;
            complexity?: string;
            task_type?: string;
            tools_included?: string[];
            validation_passed?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            deployment_count?: number;
        };
        AgentUpdateRequest: {
            description?: string;
            flow_code?: string;
            agents_config?: Record<string, never>;
        };
        HealthResponse: {
            /** @enum {string} */
            status?: "healthy" | "degraded" | "unhealthy";
            version?: string;
            /** Format: date-time */
            timestamp?: string;
            checks?: {
                database?: components["schemas"]["HealthCheck"];
                redis?: components["schemas"]["HealthCheck"];
                llm_provider?: components["schemas"]["HealthCheck"];
            };
            metrics?: {
                total_agents?: number;
                cache_hits?: number;
                cache_misses?: number;
            };
        };
        HealthCheck: {
            /** @enum {string} */
            status?: "healthy" | "unhealthy";
            latency_ms?: number;
            message?: string;
        };
        ErrorResponse: {
            /** @description Error type */
            error?: string;
            /** @description Human-readable error message */
            message?: string;
            /** @description Additional details */
            detail?: string;
            /** @description Machine-readable error code */
            error_code?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        RegenerateRequest: {
            /** Format: uuid */
            agent_id: string;
            /** @description Description of modifications to make */
            modifications?: string;
            /** @enum {string} */
            new_complexity?: "simple" | "moderate" | "complex";
            add_tools?: string[];
            remove_tools?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateAgentRequest"];
            };
        };
        responses: {
            /** @description Agent generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateAgentResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Generation failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    regenerateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Agent regenerated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateAgentResponse"];
                };
            };
        };
    };
    validateCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateCodeRequest"];
            };
        };
        responses: {
            /** @description Validation complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateCodeResponse"];
                };
            };
        };
    };
    getValidationRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of validation rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rules?: {
                            name?: string;
                            description?: string;
                            /** @enum {string} */
                            severity?: "error" | "warning" | "info";
                        }[];
                    };
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                task_type?: string;
                complexity?: "simple" | "moderate" | "complex";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentListResponse"];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailResponse"];
                };
            };
            /** @description Agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdateRequest"];
            };
        };
        responses: {
            /** @description Agent updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailResponse"];
                };
            };
        };
    };
    deleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service is unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readinessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    livenessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
