/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy agent to container
         * @description Deploy a generated agent to a new Docker container.
         *     Uses the No-Build strategy - mounts code into pre-built image.
         */
        post: operations["deployAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deploy/{deployment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove deployment
         * @description Stop and remove a deployed agent container
         */
        delete: operations["removeDeployment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all containers
         * @description Retrieve a list of all LAIAS agent containers
         */
        get: operations["listContainers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{container_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get container details */
        get: operations["getContainer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{container_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start container */
        post: operations["startContainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{container_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop container */
        post: operations["stopContainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{container_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart container */
        post: operations["restartContainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{container_id}/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute command in container */
        post: operations["execInContainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{container_id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove container */
        delete: operations["removeContainer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{container_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get container metrics */
        get: operations["getContainerMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{container_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get container logs
         * @description Retrieve logs from a container with pagination support
         */
        get: operations["getContainerLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{container_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream container logs
         * @description Stream logs in real-time via Server-Sent Events
         */
        get: operations["streamContainerLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check */
        get: operations["readinessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["livenessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeployAgentRequest: {
            /**
             * Format: uuid
             * @description ID of the generated agent
             */
            agent_id: string;
            /** @description Python code (flow.py) */
            flow_code: string;
            /** @description YAML configuration (agents.yaml) */
            agents_yaml: string;
            /** @description Optional requirements.txt content */
            requirements?: string;
            /**
             * @description Start container after creation
             * @default true
             */
            auto_start: boolean;
            /** @description Environment variables */
            environment?: {
                [key: string]: string;
            };
            /**
             * @description Memory limit (e.g., 256m, 1g)
             * @default 256m
             */
            memory_limit: string;
            /**
             * @description CPU limit (number of cores)
             * @default 1
             */
            cpu_limit: number;
            /**
             * @description Maximum execution time
             * @default 3600
             */
            timeout_seconds: number;
            /**
             * @description Docker network to use
             * @default laias-network
             */
            network: string;
        };
        DeploymentResponse: {
            /** @description Unique deployment identifier */
            deployment_id?: string;
            /** @description Docker container ID */
            container_id?: string;
            /** @description Human-readable container name */
            container_name?: string;
            /** Format: uuid */
            agent_id?: string;
            /** @enum {string} */
            status?: "created" | "running" | "stopped" | "error";
            /** @description Exposed port */
            port?: number;
            endpoints?: {
                /** Format: uri */
                logs?: string;
                /** Format: uri */
                metrics?: string;
            };
            /** Format: date-time */
            created_at?: string;
            message?: string;
        };
        ContainerListResponse: {
            containers?: components["schemas"]["ContainerInfo"][];
            total?: number;
        };
        ContainerInfo: {
            container_id?: string;
            name?: string;
            agent_id?: string;
            agent_name?: string;
            /** @enum {string} */
            status?: "running" | "stopped" | "paused" | "exited" | "error";
            state?: string;
            image?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            started_at?: string;
            ports?: {
                container_port?: number;
                host_port?: number;
                protocol?: string;
            }[];
            labels?: {
                [key: string]: string;
            };
            resource_usage?: components["schemas"]["ResourceUsage"];
        };
        ResourceUsage: {
            cpu_percent?: number;
            memory_usage?: string;
            memory_percent?: number;
            network_rx_bytes?: number;
            network_tx_bytes?: number;
        };
        ActionResponse: {
            success?: boolean;
            container_id?: string;
            status?: string;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ExecResponse: {
            exit_code?: number;
            output?: string;
        };
        LogsResponse: {
            container_id?: string;
            logs?: {
                /** Format: date-time */
                timestamp?: string;
                /** @enum {string} */
                level?: "debug" | "info" | "warning" | "error";
                message?: string;
                raw?: string;
            }[];
            total_lines?: number;
            has_more?: boolean;
            offset?: number;
        };
        MetricsResponse: {
            container_id?: string;
            /** Format: date-time */
            timestamp?: string;
            cpu?: {
                percent?: number;
                usage_seconds?: number;
            };
            memory?: {
                usage_bytes?: number;
                limit_bytes?: number;
                percent?: number;
            };
            network?: {
                rx_bytes?: number;
                tx_bytes?: number;
                rx_packets?: number;
                tx_packets?: number;
            };
            io?: {
                read_bytes?: number;
                write_bytes?: number;
            };
        };
        HealthResponse: {
            /** @enum {string} */
            status?: "healthy" | "degraded" | "unhealthy";
            version?: string;
            /** Format: date-time */
            timestamp?: string;
            checks?: {
                database?: components["schemas"]["HealthCheck"];
                redis?: components["schemas"]["HealthCheck"];
                docker?: components["schemas"]["HealthCheck"];
            };
            metrics?: {
                total_deployments?: number;
                running_containers?: number;
                total_containers?: number;
            };
        };
        HealthCheck: {
            /** @enum {string} */
            status?: "healthy" | "unhealthy";
            latency_ms?: number;
            message?: string;
        };
        ErrorResponse: {
            /** @description Machine-readable error code */
            error_code?: string;
            /** @description Error type */
            error?: string;
            /** @description Human-readable error message */
            message?: string;
            detail?: string;
            /** Format: date-time */
            timestamp?: string;
            container_id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    deployAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployAgentRequest"];
            };
        };
        responses: {
            /** @description Agent deployed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent already deployed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Deployment failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Deployment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listContainers: {
        parameters: {
            query?: {
                /** @description Include stopped containers */
                all?: boolean;
                status?: "running" | "stopped" | "paused" | "all";
                /** @description Filter by agent ID */
                agent_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of containers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerListResponse"];
                };
            };
        };
    };
    getContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Container details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerInfo"];
                };
            };
            /** @description Container not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Container started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Container not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Container already running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stopContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Seconds to wait before killing
                     * @default 10
                     */
                    timeout?: number;
                };
            };
        };
        responses: {
            /** @description Container stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Container not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restartContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default 10 */
                    timeout?: number;
                };
            };
        };
        responses: {
            /** @description Container restarted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
        };
    };
    execInContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example [
                     *       "python",
                     *       "-c",
                     *       "print('hello')"
                     *     ]
                     */
                    command: string[];
                };
            };
        };
        responses: {
            /** @description Command executed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecResponse"];
                };
            };
        };
    };
    removeContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default false */
                    force?: boolean;
                    /** @default false */
                    remove_volumes?: boolean;
                };
            };
        };
        responses: {
            /** @description Container removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Container not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getContainerMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Container metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
    getContainerLogs: {
        parameters: {
            query?: {
                /** @description Number of lines to return from end */
                tail?: number;
                /** @description Only return logs since this timestamp */
                since?: string;
                /** @description Include timestamps */
                timestamps?: boolean;
                /** @description Pagination offset */
                offset?: number;
                /** @description Max number of log lines */
                limit?: number;
            };
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Container logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
            /** @description Container not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamContainerLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of log events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readinessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    livenessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
